version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST : localhost
      USER_DB : root
      PASSWORD : 22081991
      DB_NAME : Avito
    command: 
      - make create_base
      - make coverage
      - make run
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 22081991