version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST : 127.0.0.1:33060
      USER_DB : root
      PASSWORD : 22081991
      DB_NAME : Avito
    ports:
     - "8000:8000"
    volumes:
      - ".:/avito"
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 22081991