version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST : 127.0.0.1:3306
      USER_DB : lol
      PASSWORD : secret
      DB_NAME : Avito
    ports:
     - "8000:8000"
    volumes:
      - ".:/avito"
    depends_on:
      - db
    command: make docker
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      - MYSQL_DATABASE= Avito
      - MYSQL_USER= lol
      - MYSQL_PASSWORD= secret
      - MYSQL_ROOT_PASSWORD= secret